const SOCKET_ON_BROADCAST_GAMESTATE = 'broadcastGameState';
const SOCKET_ON_JOIN_ROOM = 'joinRoom';
const SOCKET_ON_SOCKETID = 'getSocketId';
const SOCKET_ON_REJECT_PLAYER = 'rejectPlayer';
const SOCKET_ON_LEAVE_ROOM = 'leaveRoom';

const SOCKET_EMIT_SOCKETID = 'socketId';
const SOCKET_EMIT_PLAYER_JOINED_FAILED = 'playerJoinedFailed';
const SOCKET_EMIT_PLAYER_JOINED = 'playerJoined';
const SOCKET_EMIT_UPDATE_GAMESTATE = 'updateGameState';
const SOCKET_EMIT_PLAYER_REJECTED = 'playerRejected';

module.exports = {
    SOCKET_ON_BROADCAST_GAMESTATE,
    SOCKET_ON_JOIN_ROOM,
    SOCKET_ON_SOCKETID,
    SOCKET_ON_REJECT_PLAYER,
    SOCKET_ON_LEAVE_ROOM,
    SOCKET_EMIT_SOCKETID,
    SOCKET_EMIT_PLAYER_JOINED_FAILED,
    SOCKET_EMIT_PLAYER_JOINED,
    SOCKET_EMIT_UPDATE_GAMESTATE,
    SOCKET_EMIT_PLAYER_REJECTED
};